name: iridium_app
description: A Flutter app for eBooks
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Managed by CodeMagic. See https://docs.codemagic.io/configuration/build-versioning/
# version: 0.0.1+2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mno_commons:
    path: ../components/commons
  mno_navigator:
    path: ../components/navigator
  mno_server:
    path: ../components/server
  mno_streamer:
    path: ../components/streamer
  mno_opds:
    path: ../components/opds
  mno_shared:
    path: ../components/shared
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  #  flutter_icons: ^1.1.0
  flutter_font_icons: ^2.2.4
  xml2json: ^5.3.2
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0
  dartx: ^1.0.0
  uuid: ^3.0.5
  objectdb: ^1.2.1+1
  path_provider: ^2.0.8
  dio: ^4.0.4
  permission_handler: ^8.3.0
  google_fonts: ^2.2.0
  flutter_spinkit: ^5.1.0
  idb_shim: ^2.0.1
  idb_sqflite: ^1.1.0
  sqflite_common_ffi: ^2.1.0+2
  flutter_fimber: ^0.6.4
  fimber: ^0.6.4
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  flutter_inappwebview: ^5.3.2
  json_theme: ^3.2.5
  new_version: ^0.3.0

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/appainter_light_theme.json
    - assets/appainter_dark_theme.json
